export const englishConstants = {
  Salam: "Salam",
  Home: "Home",
  AboutUs: "About Us",
  OurStoryVideo:
    "https://www.youtube.com/watch?v=Okn0WpJqgHE&ab_channel=aliciakeysVEVO",
  SignUpTitle: "Sign up as a ",
  Volunteer: "Volunteer",
  Disabled: "Disabled Person",
  CharityInstitution: "Charity Institution",
  Name:"Name",
  NamePlaceHolder:"Sharukhan Metwally ",
  Password:"Password",
  PasswordPlaceHolder:"A password must have a special character, letter and number example : OreoMadness94!",
  Email:"Email",
  EmailPlaceHolder:"email@example.duhh ",
  PhoneNumber: "Phone Number", 
  PhoneNumberPlaceHolder: "0100000000 ",
  ReferralCode: "Referral Code",
  ReferralCodePlaceHolder: "Enter code",
  UploadIdFront: "Upload Id (Front Side)",
  UploadIdBack: "Upload Id (Back side)",
  FbProfileLink: "Facebook Profile Link",
  FbPlaceHolder: "75% of salam users believe that having a facebook link is safer",
  DisablityProof: "A Proof of disabilty for example كارنيه الخدمات المتاكملة or شهادة التأهيل",
  ProofApology: "We're sorry we have to ask for proof but it's to ensure the safety of all parties. We hope you understand.",
  Gender: "Gender",
  Photo: "Personal picture",
  GenderPlaceHolder: "Click here to choose your gender",
  Male:"male",
  Female: "female",
  ChooseFile: "Choose a file",
  ThankYou: "Thank you so much!",
  ThankYouBody: "ًWe're honoured you want to join us! Your application will be reviewed and someone from our team will contact you, SALAM.",
};

export const arabicConstants = {
  Salam: "سلام",
  Home: "الرئيسية",
  AboutUs: "معلومات عنا",
  OurStoryVideo:
    "https://www.youtube.com/watch?v=KLmSWs4tWbk&ab_channel=BanqueMisr",
  SignUpTitle: "أنضم لينا",
  Volunteer: "متطوع",
  Disabled: "أصحاب الهمم",
  CharityInstitution: " جمعية خيرية",
  Name:"الأسم",
  NamePlaceHolder:"شاروخان متولي",
  Password:"كلمة السر",
  PasswordPlaceHolder:" أدخل كلمة السر محتوية على علامة مميزة و حروف و أرقام مثلا Mohamed1!",
  Email:"البريد الألكتروني",
  EmailPlaceHolder:"مثلا fa3elKheir@Salam.com",
  PhoneNumber: "رقم التليفون", 
  PhoneNumberPlaceHolder: "أدخل رقم التليفون زي كدة 01000000000",
  ReferralCode: "كود الدعوة",
  ReferralCodePlaceHolder: "ادخل الكود",
  UploadIdFront: "صورة البطاقة من الأمام",
  UploadIdBack: "صورة البطاقة من الخلف      ",
  FbProfileLink: "لينك حساب الفيسبوك الخاص بيك",
  FbPlaceHolder: "75% من مستخدمي سلام شايفين ان وجود حساب فيسبوك هيطمنهم من ناحيتك أكتر",
  DisablityProof: "اثبات أنكم من أصحاب الهمم ممكن كارنيه الخدمات المتاكملة أو شهادة التأهيل",
  ProofApology: "بنعتذر على اننا بنطلب اثبات بس علشان نضمن أمن جميع الأطراف. نتمني أنكم تكونوا متفهمين.",
  Gender: "النوع",
  Photo: "صورة شخصية",
  GenderPlaceHolder: "دوس هنا علشان تختار النوع",
  Male:"ذكر",
  Female: "أنثى",
  ChooseFile: "اختار صورة",
  ThankYou: "متشكرين جدا ليكم! ",
  ThankYouBody: "متشرفين أنكم حابين تنضموا لينا, في حد من فريقنا هايرجع طلبكم و يتواصل معاكم. سلام",
};

